//{{NO_DEPENDENCIES}}
// LocalSendXP resource identifiers
//
#define IDR_MAINMENU                    101
#define IDR_ACCELERATOR                 102
#define IDI_APP                         103
#define IDI_SMALL                       104
#define IDI_TOOL_SEND_FOLDER            105
#define IDI_TOOL_FROM_URL               106
#define IDI_TOOL_OPEN_FOLDER            107
#define IDI_TOOL_SETTINGS               108
#define IDI_TOOL_ABOUT                  109
#define IDI_TOOL_HISTORY                110

#define IDD_ABOUT                       110
#define IDD_SETTINGS                    111
#define IDD_RECEIVE                     112
#define IDD_PIN                         113
#define IDD_SHARE                       114
#define IDD_URL                         115
#define IDD_HELP                        116
#define IDD_SETTINGS_GENERAL            120
#define IDD_SETTINGS_TRANSFER           121
#define IDD_SETTINGS_NETWORK            122
#define IDD_SETTINGS_SECURITY           123
#define IDD_HISTORY                     124

// ---- string table -------------------------------------------------------
#define IDS_APP_TITLE                   200
#define IDS_APP_SUBTITLE                201
#define IDS_STATUS_ONLINE               202
#define IDS_STATUS_OFFLINE              203
#define IDS_STATUS_SCANNING             204
#define IDS_STATUS_LISTENING            205
#define IDS_STATUS_DEVFMT               206
#define IDS_STATUS_SELFFMT              207
#define IDS_GROUP_DEVICES               208
#define IDS_GROUP_TRANSFERS             209
#define IDS_COL_NAME                    210
#define IDS_COL_MODEL                   211
#define IDS_COL_TYPE                    212
#define IDS_COL_ADDR                    213
#define IDS_COL_SEEN                    214
#define IDS_COL_FILE                    215
#define IDS_COL_SIZE                    216
#define IDS_COL_PROGRESS                217
#define IDS_COL_SPEED                   218
#define IDS_COL_ETA                     219
#define IDS_COL_STATE                   220
#define IDS_COL_DIR                     221
#define IDS_BTN_SEND                    222
#define IDS_BTN_REFRESH                 223
#define IDS_BTN_SETTINGS                224
#define IDS_TYPE_MOBILE                 225
#define IDS_TYPE_DESKTOP                226
#define IDS_TYPE_WEB                    227
#define IDS_TYPE_HEADLESS               228
#define IDS_TYPE_SERVER                 229
#define IDS_TYPE_UNKNOWN                230
#define IDS_DIR_SEND                    231
#define IDS_DIR_RECV                    232
#define IDS_ST_WAITING                  233
#define IDS_ST_TRANSFER                 234
#define IDS_ST_DONE                     235
#define IDS_ST_FAILED                   236
#define IDS_ST_CANCELED                 237
#define IDS_ST_DENIED                   238
#define IDS_ST_PINWAIT                  239
#define IDS_MSG_SELECT_DEVICE           240
#define IDS_MSG_NO_FILES                241
#define IDS_MSG_SENDFAIL                242
#define IDS_MSG_OPENFOLDER_FAIL         243
#define IDS_MSG_PORTBUSY                244
#define IDS_MSG_TRAYHINT                245
#define IDS_MSG_RESTART_REQUIRED        246
#define IDS_MSG_NOTIFY_TITLE            247
#define IDS_MSG_RECEIVED                248
#define IDS_MSG_RECEIVED_PARTIAL        249
#define IDS_MSG_TRANSFER_SENT           250
#define IDS_FILTER_FILES                251
#define IDS_TITLE_SFILES                252
#define IDS_TITLE_SFOLDER               253
#define IDS_RECEIVE_TITLE               254
#define IDS_FMT_RECEIVE_INFO            255
#define IDS_RECEIVE_ACCEPT              256
#define IDS_RECEIVE_DENY                257
#define IDS_PIN_TITLE                   258
#define IDS_PIN_INFO                    259
#define IDS_PIN_WRONG                   260
#define IDS_SETTINGS_TITLE              261
#define IDS_SET_ALIAS                   262
#define IDS_SET_TYPE                    263
#define IDS_SET_MODEL                   264
#define IDS_SET_PORT                    265
#define IDS_SET_DIR                     266
#define IDS_SET_BROWSE                  267
#define IDS_SET_AUTOSTART               268
#define IDS_SET_TRAY                    269
#define IDS_SET_ASK                     270
#define IDS_SET_PIN                     271
#define IDS_SET_OPENAFTER               272
#define IDS_SET_ERR_PORT                273
#define IDS_SET_ERR_DIR                 274
#define IDS_SHARE_TITLE                 275
#define IDS_SHARE_INFO                  276
#define IDS_SHARE_COPY                  277
#define IDS_SHARE_COPIED                278
#define IDS_ABOUT_INFO                  279
#define IDS_ABOUT_PROTOCOL              280
#define IDS_ABOUT_CREDIT                281
#define IDS_LOG_OPENFAIL                283
#define IDS_MSG_SENT_TO                 284
#define IDS_ST_BLOCKED                  285
#define IDS_MSG_PIN_REQUIRED            286
#define IDS_MSG_DEVICE_BUSY             287
#define IDS_MSG_REJECTED                288
#define IDS_MSG_NONAME                  289
#define IDS_MSG_BADNAME                 290
#define IDS_MSG_PATH_TOO_LONG           291
#define IDS_MSG_SAVE_FAIL               292
#define IDS_MSG_SHARE_EMPTY             293
#define IDS_MSG_SECURITY                294
#define IDS_ST_FOLDER                   295
#define IDS_MSG_FOLDER_SKIP             296
#define IDS_MENU_SHOW                   297
#define IDS_MENU_SEND                   298
#define IDS_MENU_OPENFOLDER             299
#define IDS_MENU_SETTINGS               300
#define IDS_MENU_EXIT                   301
#define IDS_MSG_CANCEL_TRANSFER         302
#define IDS_MSG_NO_ACTIVE_TRANSFER      303
#define IDS_TIME_JUSTNOW                304
#define IDS_TIME_SECONDS_AGO            305
#define IDS_TIME_MINUTES_AGO            306
#define IDS_FONT_FACE                   307
#define IDS_BROWSE_TITLE                308
#define IDS_ETA_LESS_SEC                309
#define IDS_ETA_SECONDS                 310
#define IDS_ETA_MINUTE_SECOND           311
#define IDS_ETA_HOUR_MINUTE             312
#define IDS_WEB_EMPTY                   313
#define IDS_WEB_STALE                   314
#define IDS_WEB_TOTAL                   315
#define IDS_WEB_COL_FILE                316
#define IDS_WEB_COL_SIZE                317
#define IDS_MSG_ENCRYPTED_PEER          318
#define IDS_SUFFIX_ENCRYPTED            319
#define IDS_MSG_FILES_SKIPPED           320
#define IDS_TB_SENDFOLDER               322
#define IDS_TB_SETTINGS                 324
#define IDS_TB_OPENFOLDER               325
#define IDS_TB_ABOUT                    326
#define IDS_TB_FROMURL                  329
#define IDS_MSG_HISTORY_CLEARED         327
#define IDS_MSG_CLEAR_FINISHED          328
#define IDS_URL_INFO                    330
#define IDS_URL_HINT                    331
#define IDS_MSG_URL_INVALID             332
#define IDS_MSG_URL_HTTPS               333
#define IDS_MSG_TLS_MISSING             350
#define IDS_SET_HTTPS                   351
#define IDS_SET_LEGACY                  352
#define IDS_SET_INSECURE                353
#define IDS_SET_CLIENTCERT              354
#define IDS_GRP_SECURITY                355
#define IDS_STATUS_HTTPS                356
#define IDS_ABOUT_TLS_OFF               357
#define IDS_MSG_TLS_NOFINGERPRINT       358
#define IDS_MSG_HTTPS_DISABLED          359
#define IDS_SET_TAB_GENERAL             360
#define IDS_SET_TAB_TRANSFER            361
#define IDS_SET_TAB_NETWORK             362
#define IDS_SET_TAB_SECURITY            363
#define IDS_SET_LANGUAGE                364
#define IDS_LANG_ZH                     365
#define IDS_LANG_EN                     366
#define IDS_MSG_LANG_CHANGED            367
#define IDS_SET_GROUP_DEVICE            368
#define IDS_SET_GROUP_BEHAVIOR          369
#define IDS_SET_GROUP_FILES             370
#define IDS_SET_GROUP_PROTECT           371
#define IDS_SET_GROUP_NET               372
#define IDS_SET_GROUP_TLS               373
#define IDS_SET_DEVICE_INFO             374
#define IDS_SET_ANNOUNCE                375
#define IDS_SET_CERT_PATH               376
#define IDS_SET_CABUNDLE_PATH           377
#define IDS_SET_FINGERPRINT             378
#define IDS_SET_NOTE                    379
#define IDS_LBL_ALIAS                   380
#define IDS_LBL_TYPE                    381
#define IDS_LBL_MODEL                   382
#define IDS_LBL_PORT                    383
#define IDS_LBL_PIN                     384
#define IDS_LBL_PIN_HINT                385
#define IDS_LBL_DIR                     386
#define IDS_CHK_ASK                     387
#define IDS_CHK_OPENAFTER               388
#define IDS_CHK_TRAY                    389
#define IDS_CHK_AUTOSTART               390
#define IDS_BTN_BROWSE                  391
#define IDS_BTN_BROWSEFILE              392
#define IDS_BTN_OK                      393
#define IDS_BTN_CANCEL                  394
#define IDS_BTN_CLOSE                   395
#define IDS_BTN_SOURCE                  396
#define IDS_MENU_FILE                   400
#define IDS_MENU_DEVICE                 401
#define IDS_MENU_TOOLS                  402
#define IDS_MENU_HELP                   403
#define IDS_MENU_ITEM_SEND              404
#define IDS_MENU_ITEM_SENDFOLDER        405
#define IDS_MENU_ITEM_SHARE             406
#define IDS_MENU_ITEM_FROMURL           407
#define IDS_MENU_ITEM_REFRESH           408
#define IDS_MENU_ITEM_SENDSEL           409
#define IDS_MENU_ITEM_OPENFOLDER        410
#define IDS_MENU_ITEM_SETTINGS          411
#define IDS_MENU_ITEM_TRAY              412
#define IDS_MENU_ITEM_AUTOSTART         413
#define IDS_MENU_ITEM_LOG               414
#define IDS_MENU_ITEM_HELP              415
#define IDS_MENU_ITEM_PROTOCOL          416
#define IDS_MENU_ITEM_ABOUT             417
#define IDS_HELP_TITLE                  334
#define IDS_HELP_TEXT                   335
#define IDS_ABOUT_TITLE                 420
#define IDS_ABOUT_AUTHOR                421
#define IDS_HISTORY_TITLE               422
#define IDS_HIST_COL_TIME               423
#define IDS_HIST_COL_PEER               424
#define IDS_HIST_COL_LOCATION           425
#define IDS_HIST_OPEN                   426
#define IDS_HIST_DELETE                 427
#define IDS_HIST_CLEAR                  428
#define IDS_HIST_SUMMARY                429
#define IDS_HIST_EMPTY                  430
#define IDS_HIST_HINT                   431
#define IDS_HIST_DELETE_CONFIRM         432
#define IDS_HIST_CLEAR_CONFIRM          433
#define IDS_HIST_NO_SELECTION           434
#define IDS_HIST_OPENFAIL               435
#define IDS_HIST_DELETED                436
#define IDS_HIST_MISSING                437
#define IDS_TB_HISTORY                  438
#define IDS_MENU_ITEM_HISTORY           439

// ---- commands -----------------------------------------------------------
#define IDM_FILE_SEND                   40001
#define IDM_FILE_SHARE                  40002
#define IDM_FILE_EXIT                   40003
#define IDM_FILE_SENDFOLDER             40004
#define IDM_FILE_FROMURL                40005
#define IDM_DEVICE_REFRESH              40010
#define IDM_DEVICE_SEND                 40011
#define IDM_DEVICE_OPENFOLDER           40012
#define IDM_TOOLS_SETTINGS              40020
#define IDM_TOOLS_TRAY                  40021
#define IDM_TOOLS_AUTOSTART             40022
#define IDM_TOOLS_LOG                   40023
#define IDM_TOOLS_HISTORY               40024
#define IDM_HELP_PROTOCOL               40030
#define IDM_HELP_GUIDE                  40031
#define IDM_HELP_ABOUT                  40032
#define IDM_TRANSFER_CANCEL             40040
#define IDM_TRANSFER_CLEAR              40041

// ---- controls -----------------------------------------------------------
#define IDC_STATIC                      -1
#define IDC_DEVICE_LIST                 1000
#define IDC_TRANSFER_LIST               1001
#define IDC_BTN_SEND                    1002
#define IDC_BTN_REFRESH                 1003
#define IDC_BTN_SETTINGS                1004
#define IDC_STATUSBAR                   1005
#define IDC_PROGRESS                    1006
#define IDC_DEVICE_GROUP                1007
#define IDC_TRANSFER_GROUP              1008
#define IDC_DEVICE_LABEL                1009
#define IDC_TRANSFER_LABEL              1010
#define IDC_RECEIVE_LIST                1020
#define IDC_RECEIVE_INFO                1021
#define IDC_SET_ALIAS                   1030
#define IDC_SET_TYPE                    1031
#define IDC_SET_MODEL                   1032
#define IDC_SET_PORT                    1033
#define IDC_SET_PIN                     1034
#define IDC_SET_DIR                     1035
#define IDC_SET_BROWSE                  1036
#define IDC_SET_ASK                     1037
#define IDC_SET_TRAY                    1038
#define IDC_SET_AUTOSTART               1039
#define IDC_SET_OPENAFTER               1040
#define IDC_PIN_EDIT                    1041
#define IDC_SHARE_URL                   1042
#define IDC_SHARE_COPY                  1043
#define IDC_TOOLBAR                     1044
#define IDC_URL_EDIT                    1045
#define IDC_SET_HTTPS                   1060
#define IDC_SET_LEGACY                  1061
#define IDC_SET_INSECURE                1062
#define IDC_SET_CLIENTCERT              1063
#define IDC_SET_TABS                    1070
#define IDC_SET_LANGUAGE                1071
#define IDC_SET_DEVICE_INFO             1072
#define IDC_SET_FINGERPRINT             1073
#define IDC_SET_CERT                    1074
#define IDC_SET_CABUNDLE                1075
#define IDC_SET_CERT_BROWSE             1076
#define IDC_SET_CA_BROWSE               1077
#define IDC_SET_ANNOUNCE                1078
#define IDC_SET_NOTE                    1080
#define IDC_GRP_DEVICE                  1081
#define IDC_LBL_ALIAS                   1082
#define IDC_LBL_TYPE                    1083
#define IDC_LBL_MODEL                   1084
#define IDC_LBL_LANGUAGE                1085
#define IDC_GRP_BEHAVIOR                1086
#define IDC_GRP_FILES                   1087
#define IDC_LBL_DIR                     1088
#define IDC_GRP_PROTECT                 1089
#define IDC_LBL_PIN                     1090
#define IDC_LBL_PIN_HINT                1091
#define IDC_GRP_NET                     1092
#define IDC_LBL_PORT                    1093
#define IDC_LBL_ANNOUNCE                1094
#define IDC_LBL_ADDR                    1095
#define IDC_GRP_TLS                     1096
#define IDC_LBL_FP                      1097
#define IDC_GRP_CERT                    1098
#define IDC_LBL_CERT                    1099
#define IDC_LBL_CA                      1100
#define IDC_SHARE_INFO                  1101
#define IDC_HELP_TEXT                   1046
#define IDC_ABOUT_AUTHOR                1047
#define IDC_ABOUT_SOURCE                1048
#define IDC_URL_INFO                    1102
#define IDC_URL_HINT                    1103
#define IDC_ABOUT_NAME                  1104
#define IDC_ABOUT_SUBTITLE              1105
#define IDC_ABOUT_INFO                  1106
#define IDC_ABOUT_PROTOCOL              1107
#define IDC_ABOUT_CREDIT                1108
#define IDC_PIN_INFO                    1109
#define IDC_HIST_LIST                   1110
#define IDC_HIST_SUMMARY                1111
#define IDC_HIST_OPEN                   1112
#define IDC_HIST_DELETE                 1113
#define IDC_HIST_CLEAR                  1114
#define IDC_HIST_HINT                   1115
